name: gpt_markdown_viewer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  # gpt_markdown: ^1.1.5
  gpt_markdown:
    git:
      url: https://github.com/ContextFound/gpt_markdown.git
      ref: my-fork-main
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
